Helm provider/allow null values
cdibble/pulumi-kubernetes pull request #1
Opened 2022-09-27 22:41 UTC by cdibble

### Proposed changes

### Related issues (optional)

2022-09-29 15:40 UTC, lblackstone requested changes
Thanks for the contribution, @cdibble!

Overall, I think this change looks good. Just a couple items to address:

1. Update helm.Release schema and regenerate SDKs
2. Add a changelog entry

Once that's done, you can submit the pull request to the pulumi-kubernetes repo, and we can run this through CI testing.

2022-09-29 15:40 UTC, lblackstone commented on provider/pkg/provider/helm_release.go
> +	AllowNullValues bool `json:"allowNullValues,omitempty"`
You will also need to add this field to the [resource schema](https://github.com/cdibble/pulumi-kubernetes/blob/master/provider/pkg/gen/overlays.go#L532-L1026).

Once the schema is updated, you can run `make ensure build install` to generate all of the updated SDKs.

2022-09-29 15:40 UTC, lblackstone commented on provider/pkg/provider/helm_release.go
> +	AllowNullValues bool `json:"allowNullValues,omitempty"`
nit: Options should be alphabetized

2022-10-04 21:26 UTC, cdibble commented
Thanks for the feedback @lblackstone - I will address your comments and ping you when I've got an update ready. Sorry for the slow movement- I'm at a conference this week. I have an open ticket related to this and will address it as soon as I can :)

2022-10-25 16:27 UTC, cdibble commented
@lblackstone Sorry for the delay. I think this is ready to go given your commentary. Do you want to take a look at this stage? Otherwise I can just PR to `pulumi/pulumi-kubernetes`.

2022-10-27 17:21 UTC, merged